### ISSUE TITLE
correios internacional

### ISSUE THREAD

**Issue by marcelowu** [Jeffer5504/Frete-Correios#2]
https://github.com/gutobenn/woocommerce-correios-1/tree/international_shipping
pretende fazer do correios internacional tbm

**Comment by jeffeloy** [comment]
Iai Mano, não conheço a api pro correios internacional. Mas vou dar uma
olhada aqui.
Pq?

Em ter, 19 de mai de 2020 11:15, marcelowu <notifications@github.com>
escreveu:

**Comment by marcelowu** [comment]
https://cws2.correios.com.br/static/swagger/?url=/precoprazoservice/rs/swagger.json#!/Internacional/consultaPreco
